copyright: this is copyright
docs_dir: source
extra:
  article_nav_bottom: true
  history_buttons: true
  version: v1.0.4
markdown_extensions:
- admonition
nav:
- python: python.md
- index: index.md
- rsync: rsync.md
- git: git.md
repo_url: https://github.com/smaugx/wiki
site_author: smaugx
site_description: my wiki
site_dir: docs
site_name: My Wiki
site_url: http://rebootcat.com/wiki
theme:
  custom_dir: mkdocs_windmill
  include_search_page: true
  name: null
  search_index_only: true
  static_templates:
  - 404.html
