site_name: My Wiki
site_url: http://rebootcat.com/wiki
site_author: smaugx
site_description: "my wiki"
repo_url: "https://github.com/smaugx/wiki.git"
copyright: "this is copyright"

theme:
  name: null
  custom_dir: mkdocs_windmill
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true


nav:
    - Home: 'index.md'
    - Cmake: 'cmake.md'
    - Scons: 'scons_build_cplusplus.md'
    - Scons2: 'scons2.md'
    - Scons3: 'scons3.md'
    - Scons4: 'scons4.md'
    - Scons5: 'scons5.md'
    - Scons6: 'scons6.md'
    - Scons7: 'scons7.md'
    - Scons8: 'scons8.md'
    - Scons9: 'scons9.md'
    - auto-run-aliyun-spot: 'auto_run_aliyun_spot.md'



markdown_extensions:
  - admonition

extra:
    history_buttons: true
    version: v1.0.4
    article_nav_bottom: true
