copyright: "Copyright \xA9 2020-2020 smaug"
docs_dir: source
extra:
  article_nav_bottom: true
  history_buttons: true
  version: v1.0.4
markdown_extensions:
- admonition
nav:
- Home: index.md
- python: python.md
- rsync: rsync.md
- git: git.md
- "\u5176\u4ED6": other.md
repo_url: https://github.com/smaugx/wiki
site_author: smaugx
site_description: "My Wiki | \u6797\u5915\u6C34\u5171"
site_dir: docs
site_name: "My Wiki | \u6797\u5915\u6C34\u5171"
site_url: http://rebootcat.com/wiki
theme:
  custom_dir: mkdocs_windmill
  include_search_page: true
  name: null
  search_index_only: true
  static_templates:
  - 404.html
